/**
 * @remirdy/shared — workflowPresets.ts
 * Predefined workflow recipes for common document types.
 * All content is public-safe and fictional.
 */

import type { DesignJson } from "./jobTypes.js";

// ─── Premium Mobile Game UI ───────────────────────────────────────────────────

export const PREMIUM_MOBILE_GAME_UI: DesignJson = {
  document: {
    name: "ColorCrateSort_GameplayUI_Demo",
    width: 1290,
    height: 2796,
    backgroundColor: "#140B2E",
    resolution: 72,
    colorMode: "RGB",
  },
  groups: [
    "01_BG",
    "02_GAMEPLAY_SCENE/Game_Board",
    "02_GAMEPLAY_SCENE/Puzzle_Area",
    "02_GAMEPLAY_SCENE/Tile_Placeholders",
    "02_GAMEPLAY_SCENE/Crate_Row",
    "02_GAMEPLAY_SCENE/Lighting_FX",
    "03_UI/Top_HUD/Coin_Counter",
    "03_UI/Top_HUD/Level_Indicator",
    "03_UI/Top_HUD/Settings_Button",
    "03_UI/Bottom_HUD/Booster_Row",
    "04_POPUP/Scrim",
    "04_POPUP/Modal",
    "05_EXPORT_NOTES",
  ],
  layers: [
    // BG
    {
      type: "shape",
      kind: "rectangle",
      name: "BG_Base",
      x: 0,
      y: 0,
      width: 1290,
      height: 2796,
      fill: "#140B2E",
      parentGroup: "01_BG",
    },
    {
      type: "shape",
      kind: "rectangle",
      name: "BG_Gradient",
      x: 0,
      y: 0,
      width: 1290,
      height: 2796,
      fill: "#2A164C",
      parentGroup: "01_BG",
    },
    // Top HUD — Coin Counter
    {
      type: "shape",
      kind: "roundedRect",
      name: "CoinCounter_BG",
      x: 80,
      y: 80,
      width: 310,
      height: 96,
      radius: 36,
      fill: "#321B58",
      stroke: { color: "#6B45A0", width: 3 },
      shadow: { enabled: true, opacity: 35, blur: 18, distance: 8, angle: 90, color: "#000000" },
      parentGroup: "03_UI/Top_HUD/Coin_Counter",
    },
    {
      type: "shape",
      kind: "circle",
      name: "CoinCounter_Icon",
      x: 100,
      y: 96,
      width: 64,
      height: 64,
      fill: "#F7B833",
      stroke: { color: "#FFE08A", width: 3 },
      parentGroup: "03_UI/Top_HUD/Coin_Counter",
    },
    {
      type: "text",
      name: "CoinCounter_Text",
      text: "2,450",
      x: 190,
      y: 105,
      fontSize: 42,
      color: "#FFF2C8",
      fontFamily: "Arial Rounded MT Bold",
      align: "left",
      parentGroup: "03_UI/Top_HUD/Coin_Counter",
    },
    // Level Indicator
    {
      type: "shape",
      kind: "roundedRect",
      name: "LevelIndicator_BG",
      x: 490,
      y: 80,
      width: 310,
      height: 96,
      radius: 36,
      fill: "#321B58",
      stroke: { color: "#6B45A0", width: 3 },
      parentGroup: "03_UI/Top_HUD/Level_Indicator",
    },
    {
      type: "text",
      name: "LevelIndicator_Text",
      text: "LEVEL 12",
      x: 530,
      y: 108,
      fontSize: 44,
      color: "#FFF2C8",
      fontFamily: "Arial Rounded MT Bold",
      align: "center",
      parentGroup: "03_UI/Top_HUD/Level_Indicator",
    },
    // Settings Button
    {
      type: "shape",
      kind: "circle",
      name: "SettingsButton_BG",
      x: 1110,
      y: 80,
      width: 96,
      height: 96,
      fill: "#321B58",
      stroke: { color: "#6B45A0", width: 3 },
      parentGroup: "03_UI/Top_HUD/Settings_Button",
    },
    // Game Board
    {
      type: "shape",
      kind: "roundedRect",
      name: "GameBoard_Base",
      x: 80,
      y: 460,
      width: 1130,
      height: 1100,
      radius: 32,
      fill: "#1E0D40",
      stroke: { color: "#6B45A0", width: 4 },
      shadow: { enabled: true, opacity: 50, blur: 40, distance: 16, angle: 90, color: "#000000" },
      parentGroup: "02_GAMEPLAY_SCENE/Game_Board",
    },
    // Puzzle area placeholder
    {
      type: "shape",
      kind: "roundedRect",
      name: "PuzzleArea_Base",
      x: 120,
      y: 500,
      width: 1050,
      height: 880,
      radius: 20,
      fill: "#250E50",
      parentGroup: "02_GAMEPLAY_SCENE/Puzzle_Area",
    },
    // Export notes
    {
      type: "text",
      name: "README_Text_Layer",
      text: "LAYER STRUCTURE — Color Crate Sort Demo\nSee README_LAYER_STRUCTURE.txt for full guide.\nAll layers are editable. Group structure follows premium mobile game UI conventions.",
      x: 80,
      y: 2700,
      fontSize: 22,
      color: "#6B45A0",
      fontFamily: "Arial",
      align: "left",
      parentGroup: "05_EXPORT_NOTES",
    },
  ],
  exports: [
    { type: "psd", path: "./exports/ColorCrateSort_GameplayUI_Demo.psd" },
    { type: "png", path: "./exports/ColorCrateSort_GameplayUI_Demo.png" },
  ],
};

// ─── Confirmation Popup ───────────────────────────────────────────────────────

export const CONFIRMATION_POPUP: DesignJson = {
  document: {
    name: "ColorCrateSort_ConfirmationPopup_Demo",
    width: 1290,
    height: 2796,
    backgroundColor: "#140B2E",
  },
  groups: ["01_BG", "02_GAMEPLAY_SCENE", "03_UI", "04_POPUP/Scrim", "04_POPUP/Modal"],
  layers: [
    {
      type: "shape",
      kind: "rectangle",
      name: "BG_Base",
      x: 0,
      y: 0,
      width: 1290,
      height: 2796,
      fill: "#140B2E",
      parentGroup: "01_BG",
    },
    // Dim scrim
    {
      type: "shape",
      kind: "rectangle",
      name: "Popup_Dim_Scrim",
      x: 0,
      y: 0,
      width: 1290,
      height: 2796,
      fill: "#000000",
      parentGroup: "04_POPUP/Scrim",
    },
    // Modal panel
    {
      type: "shape",
      kind: "roundedRect",
      name: "Modal_Panel",
      x: 145,
      y: 740,
      width: 1000,
      height: 1100,
      radius: 48,
      fill: "#2A164C",
      stroke: { color: "#6B45A0", width: 3 },
      shadow: { enabled: true, opacity: 60, blur: 60, distance: 24, angle: 90, color: "#000000" },
      parentGroup: "04_POPUP/Modal",
    },
    {
      type: "text",
      name: "Modal_Title",
      text: "Exit Game?",
      x: 645,
      y: 860,
      fontSize: 72,
      color: "#FFF2C8",
      fontFamily: "Arial Rounded MT Bold",
      align: "center",
      parentGroup: "04_POPUP/Modal",
    },
    {
      type: "text",
      name: "Modal_Message",
      text: "Are you sure you want to leave?\nYour progress will not be saved.",
      x: 645,
      y: 1020,
      fontSize: 40,
      color: "#C8B8E8",
      fontFamily: "Arial",
      align: "center",
      parentGroup: "04_POPUP/Modal",
    },
    {
      type: "shape",
      kind: "roundedRect",
      name: "Confirm_Button",
      x: 245,
      y: 1600,
      width: 800,
      height: 128,
      radius: 48,
      fill: "#E8424A",
      shadow: { enabled: true, opacity: 40, blur: 20, distance: 10, angle: 90, color: "#000000" },
      parentGroup: "04_POPUP/Modal",
    },
    {
      type: "text",
      name: "Confirm_Button_Text",
      text: "LEAVE GAME",
      x: 645,
      y: 1648,
      fontSize: 48,
      color: "#FFFFFF",
      fontFamily: "Arial Rounded MT Bold",
      align: "center",
      parentGroup: "04_POPUP/Modal",
    },
    {
      type: "shape",
      kind: "circle",
      name: "Modal_Close_Button",
      x: 1060,
      y: 760,
      width: 80,
      height: 80,
      fill: "#4B2A7A",
      parentGroup: "04_POPUP/Modal",
    },
  ],
  exports: [
    { type: "psd", path: "./exports/ColorCrateSort_ConfirmationPopup_Demo.psd" },
    { type: "png", path: "./exports/ColorCrateSort_ConfirmationPopup_Demo.png" },
  ],
};

// ─── Scene Only ───────────────────────────────────────────────────────────────

export const SCENE_ONLY: DesignJson = {
  document: {
    name: "ColorCrateSort_SceneOnly_Demo",
    width: 1290,
    height: 2796,
    backgroundColor: "#140B2E",
  },
  groups: [
    "01_BG",
    "02_GAMEPLAY_SCENE/Game_Board",
    "02_GAMEPLAY_SCENE/Puzzle_Area",
    "02_GAMEPLAY_SCENE/Tile_Placeholders",
    "02_GAMEPLAY_SCENE/Crate_Row",
    "02_GAMEPLAY_SCENE/Lighting_FX",
  ],
  layers: [
    {
      type: "shape",
      kind: "rectangle",
      name: "BG_Base",
      x: 0,
      y: 0,
      width: 1290,
      height: 2796,
      fill: "#140B2E",
      parentGroup: "01_BG",
    },
    {
      type: "shape",
      kind: "roundedRect",
      name: "GameBoard_Base",
      x: 80,
      y: 300,
      width: 1130,
      height: 1400,
      radius: 32,
      fill: "#1E0D40",
      stroke: { color: "#6B45A0", width: 4 },
      parentGroup: "02_GAMEPLAY_SCENE/Game_Board",
    },
    {
      type: "shape",
      kind: "roundedRect",
      name: "PuzzleArea_Base",
      x: 120,
      y: 350,
      width: 1050,
      height: 1050,
      radius: 20,
      fill: "#250E50",
      parentGroup: "02_GAMEPLAY_SCENE/Puzzle_Area",
    },
  ],
  exports: [
    { type: "psd", path: "./exports/ColorCrateSort_SceneOnly_Demo.psd" },
    { type: "png", path: "./exports/ColorCrateSort_SceneOnly_Demo.png" },
  ],
};

// ─── Registry ────────────────────────────────────────────────────────────────

export const WORKFLOW_PRESETS: Record<string, DesignJson> = {
  premium_mobile_game_ui_case: PREMIUM_MOBILE_GAME_UI,
  game_ui_hud: PREMIUM_MOBILE_GAME_UI,
  confirmation_popup: CONFIRMATION_POPUP,
  scene_only: SCENE_ONLY,
};

export const DOCUMENT_PRESETS: Record<string, { width: number; height: number }> = {
  iphone_15_pro_max_game: { width: 1290, height: 2796 },
  instagram_post_4x5: { width: 1080, height: 1350 },
  instagram_story: { width: 1080, height: 1920 },
  app_store_screenshot: { width: 1290, height: 2796 },
  unity_ui_atlas: { width: 2048, height: 2048 },
};
