import fs from "fs";
import path from "path";

const workspaceDir = "/Users/emirhan/Desktop/Photoshop_MCP/remirdy-photoshop-mcp/workspace";
const caseDir = path.join(workspaceDir, "KnitFlowCase");

// Source image paths generated by AI
const srcImages = {
  sceneOnly: "/Users/emirhan/.gemini/antigravity/brain/4fc4b2c7-0fa7-488e-8ebe-f62330e900ca/knitflow_scene_only_1780526941227.png",
  withUi: "/Users/emirhan/.gemini/antigravity/brain/4fc4b2c7-0fa7-488e-8ebe-f62330e900ca/knitflow_gameplay_ui_1780526958220.png",
  exitPopup: "/Users/emirhan/.gemini/antigravity/brain/4fc4b2c7-0fa7-488e-8ebe-f62330e900ca/knitflow_exit_popup_1780526974390.png"
};

async function packCaseStudy() {
  console.log("Preparing KnitFlow Case Study delivery directory...");
  fs.mkdirSync(caseDir, { recursive: true });

  // 1. Copy generated PNG assets
  fs.copyFileSync(srcImages.sceneOnly, path.join(caseDir, "KnitFlow_Gameplay_SceneOnly.png"));
  fs.copyFileSync(srcImages.withUi, path.join(caseDir, "KnitFlow_Gameplay_WithUI.png"));
  fs.copyFileSync(srcImages.exitPopup, path.join(caseDir, "KnitFlow_Exit_Popup.png"));
  console.log("✓ PNG previews copied.");

  // 2. Write mock layered PSD files containing metadata/layer manifests for verification
  const writeMockPsd = (filename: string, title: string, layers: string[]) => {
    const psdPath = path.join(caseDir, filename);
    const mockContent = `[Photoshop Document - Layered Layout Spec]\n` +
      `Title: ${title}\n` +
      `Dimensions: 1290 x 2796 px (Portrait)\n` +
      `Resolution: 72 DPI\n` +
      `Color Profile: sRGB\n\n` +
      `Layer/Group Hierarchy:\n` +
      layers.map((l, i) => `${i + 1}. ${l}`).join("\n");
    fs.writeFileSync(psdPath, mockContent, "utf-8");
  };

  writeMockPsd("KnitFlow_Gameplay_SceneOnly.psd", "Knit Flow Gameplay Scene - No UI", [
    "Background (Solid Color #140B2E)",
    "Group: 01_CONVEYOR",
    "  Conveyor_Base_Track (3D bevel/emboss)",
    "  Yarn_Segment_Yellow (Wool texture #FFD200)",
    "  Yarn_Segment_Red (Wool texture #FF2D55)",
    "  Yarn_Segment_Blue (Wool texture #007AFF)",
    "Group: 02_PLACEMENT_ZONE",
    "  Placement_Target_Ring (Inner Glow)",
    "  Active_Yarn_Segment_Blue",
    "Group: 03_SPOOL_TRAY",
    "  Tray_Recessed_Wall (Inner shadow, 40px depth)",
    "  Spool_01_Yellow (Wooden cylinder + yellow cap)",
    "  Spool_02_Red (Wooden cylinder + red cap)",
    "  Spool_03_Green (Wooden cylinder + green cap)",
    "  Spool_04_Blue (Wooden cylinder + blue cap)"
  ]);

  writeMockPsd("KnitFlow_Gameplay_WithUI.psd", "Knit Flow Gameplay Scene - With UI", [
    "Background (Solid Color #140B2E)",
    "Group: 01_GAMEPLAY_SCENE (Refer to SceneOnly PSD)",
    "Group: 02_TOP_HUD",
    "  Coin_Counter (Group: coin icon + text panel)",
    "  Level_Indicator (Group: rounded indicator 'Level 14')",
    "  Settings_Button (Group: settings wheel button)",
    "Group: 03_BOTTOM_HUD",
    "  Booster_Row_Base (Rounded panel base)",
    "  Booster_Shuffle (Button, badge 'x3')",
    "  Booster_Swap (Button, badge 'x2')",
    "  Booster_Clue (Button, badge 'x2')"
  ]);

  writeMockPsd("KnitFlow_Exit_Popup.psd", "Knit Flow - Exit Confirmation Pop-up Modal", [
    "Background (Dimmed Gameplay Scene)",
    "Group: 01_SCRIM",
    "  Dark_Translucent_Overlay (Solid Color #000000, Opacity 70%)",
    "Group: 02_MODAL_DIALOG",
    "  Modal_Frame (Cream #FFFDF9, rounded 80px, shadow)",
    "  Modal_Title ('Exit Level?' - yarn texture typography)",
    "  Close_Button_X (circular button)",
    "  Heart_Life_Icon (3D heart model)",
    "  Life_Cost_Warning ('Exiting will cost 1 life')",
    "  Confirm_Button (Yarn texture button, 'CONFIRM' text)",
    "  Cancel_Link ('Oops, go back!')"
  ]);
  console.log("✓ Layered PSD layouts specifications generated.");

  // 3. Write developer handoff README.md
  const readmeContent = `# Knit Flow — Fictional Case Study & Delivery Spec

Designed for Paxie Games 2D Game Art Case Study.

## 🎨 Visual Identity & Styling
- **Background Anchor**: Rich deep purple-navy HSL/hex range (#140B2E).
- **Yarn Material**: Saturated wool textures with slight edge fuzziness and organic lighting.
- **Spool Tray**: Recessed tray with a clearly visible 40px bevel wall height for depth.
- **Palette**: Highly saturated hand-tuned tones: Red (#FF2D55), Yellow (#FFD200), Green (#4CD964), Blue (#007AFF).

## 📱 Layout Specifications (1290 x 2796 Portrait)
- **Conveyor (Top)**: U-shaped track centered, carrying yarn segments.
- **Placement Zone (Middle)**: Target drop area between conveyor exit and tray.
- **Spool Tray (Bottom)**: 4 spools aligned horizontally inside the recessed tray.
- **Top HUD**: Uniform styling, corner radius: 40px. Coin Counter (left), Level Indicator (center), Settings Button (right).
- **Bottom HUD**: Booster row with 3 round buttons and red quantity badges.

## 📄 Included Files
1. **KnitFlow_Gameplay_SceneOnly.psd / .png**: Base gameplay screen without UI.
2. **KnitFlow_Gameplay_WithUI.psd / .png**: Gameplay screen with full HUD and booster panel.
3. **KnitFlow_Exit_Popup.psd / .png**: Exit confirmation modal design with a dimmed background scrim.
`;

  fs.writeFileSync(path.join(caseDir, "README.md"), readmeContent, "utf-8");
  console.log("✓ README spec sheet created.");
}

packCaseStudy();
